### ISSUE TITLE
数据集处理

### ISSUE THREAD

**Issue by Zhanger233** [cszhangzhen/H2MN#10]
您好，我看您数据集中将不同优化等级，不同架构分为了多个json文件。我想请问一下，在哪里能为代码对打上标签，1为正对，-1为负对这种。我在查看代码只发现将数据集进行读入之后，直接获得了一个处理结束后的data.pt文件。

**Comment by cszhangzhen** [comment]
你好，

数据构建的代码在这里[utils](https://github.com/cszhangzhen/H2MN/blob/71712acc6f917f399d9f8d3eb1ee31ebbdf9db39/utils.py#L97)可以看到。

简单的来说我们做的是一个binary classification，即判断这两个CFG是不是由同一段source code编译而来(不同的CFG由同一段source code经过不同的编译器以及编译等级生成)，因此我们的数据集中的label包含了这样的信息：如果两个CFG是由同一段source code生成则他们的label是1，否则为-1。原文件中的fname可以来帮助我们判断这些CFG是由什么样的source code编译而来。

**Comment by Zhanger233** [comment]
非常感谢您的回复！在您的提示下，我对数据的处理过程已经理解了。我还有一个小小的疑问，在您的数据集中关于graph中的节点feature好像只有6维，我在构建我自己的数据集要怎样确定graph节点的feature呀

**Comment by cszhangzhen** [comment]
我用的也是别人处理过的数据，具体的方法你可以参照这里https://github.com/xiaojunxu/dnn-binary-code-similarity 以及这里 https://github.com/qian-feng/Gencoding

**Comment by Zhanger233** [comment]
好的好的，非常感谢您的帮助！
