### ISSUE TITLE
请问可微池化的消融实验有没有采用交叉图注意力机制和分层连接？

### ISSUE THREAD

**Issue by haocibuni** [cszhangzhen/H2MN#4]

**Comment by cszhangzhen** [comment]
可微池化指的是DiffPool模型么？

**Comment by haocibuni** [comment]
![image](https://user-images.githubusercontent.com/36734979/161512621-4bcee483-904d-4906-bbf8-6cd732483591.png)
对，Diffpool模型的消融实验

**Comment by cszhangzhen** [comment]
没有用交叉图注意力机制，用了hierarchical pool。你这里的分层连接指的是hierarchical pooling么？

**Comment by haocibuni** [comment]
是的，谢谢回复！
