### ISSUE TITLE
在windows执行分类任务，库的版本都一致，出现以下pyg报错

### ISSUE THREAD

**Issue by haocibuni** [cszhangzhen/H2MN#5]
Traceback (most recent call last):
  File "D:/code/python/H2MN-main/main_classification.py", line 14, in <module>
    dataset = GraphClassificationDataset(args)
  File "D:\code\python\H2MN-main\utils.py", line 87, in __init__
    self.process_dataset()
  File "D:\code\python\H2MN-main\utils.py", line 91, in process_dataset
    self.dataset = BinaryFuncDataset('datasets/{}'.format(self.args.dataset), self.args.dataset)
  File "D:\code\python\H2MN-main\utils.py", line 25, in __init__
    self.func2graph, self.number_features = torch.load(self.processed_paths[0])
  File "D:\environment\virtualenv\H2MN-main\lib\site-packages\torch\serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\environment\virtualenv\H2MN-main\lib\site-packages\torch\serialization.py", line 842, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'torch_geometric.data.storage'

Process finished with exit code 1

**Comment by haocibuni** [comment]
edge_index为什么是一行节点而不是节点对？从而导致数据在传入卷积层中出错
Traceback (most recent call last):
  File "D:/code/python/H2MN-main/main_classification.py", line 116, in <module>
    best_model = train()
  File "D:/code/python/H2MN-main/main_classification.py", line 43, in train
    prediction = model(data)
  File "D:\environment\virtualenv\Graph_Network\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\code\python\H2MN-main\models.py", line 55, in forward
    f1_conv0 = F.leaky_relu(self.conv0(features_1, edge_index_1, edge_attr_1), negative_slope=0.2)
  File "D:\environment\virtualenv\Graph_Network\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\environment\virtualenv\Graph_Network\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 164, in forward
    self.improved, self.add_self_loops)
  File "D:\environment\virtualenv\Graph_Network\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 52, in gcn_norm
    edge_weight = torch.ones((edge_index.size(1), ), dtype=dtype,
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by cszhangzhen** [comment]
> Traceback (most recent call last): File "D:/code/python/H2MN-main/main_classification.py", line 14, in dataset = GraphClassificationDataset(args) File "D:\code\python\H2MN-main\utils.py", line 87, in **init** self.process_dataset() File "D:\code\python\H2MN-main\utils.py", line 91, in process_dataset self.dataset = BinaryFuncDataset('datasets/{}'.format(self.args.dataset), self.args.dataset) File "D:\code\python\H2MN-main\utils.py", line 25, in **init** self.func2graph, self.number_features = torch.load(self.processed_paths[0]) File "D:\environment\virtualenv\H2MN-main\lib\site-packages\torch\serialization.py", line 584, in load return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args) File "D:\environment\virtualenv\H2MN-main\lib\site-packages\torch\serialization.py", line 842, in _load result = unpickler.load() ModuleNotFoundError: No module named 'torch_geometric.data.storage'
> 
> Process finished with exit code 1

这里应该是windows下文件路径分隔符的原因, 替换self.dataset = BinaryFuncDataset('datasets/{}'.format(self.args.dataset), self.args.dataset)为'datasets\\{}'.format{self.args.dataset}试试

**Comment by cszhangzhen** [comment]
> edge_index为什么是一行节点而不是节点对？从而导致数据在传入卷积层中出错 Traceback (most recent call last): File "D:/code/python/H2MN-main/main_classification.py", line 116, in best_model = train() File "D:/code/python/H2MN-main/main_classification.py", line 43, in train prediction = model(data) File "D:\environment\virtualenv\Graph_Network\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl return forward_call(*input, **kwargs) File "D:\code\python\H2MN-main\models.py", line 55, in forward f1_conv0 = F.leaky_relu(self.conv0(features_1, edge_index_1, edge_attr_1), negative_slope=0.2) File "D:\environment\virtualenv\Graph_Network\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl return forward_call(*input, **kwargs) File "D:\environment\virtualenv\Graph_Network\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 164, in forward self.improved, self.add_self_loops) File "D:\environment\virtualenv\Graph_Network\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 52, in gcn_norm edge_weight = torch.ones((edge_index.size(1), ), dtype=dtype, IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

edge_index是一个2 x |e|的数组

**Comment by haocibuni** [comment]
this my dataset directory,Is there any error?
![image](https://user-images.githubusercontent.com/36734979/163675208-e270043c-d845-4f5d-95ad-5dff21bfd36c.png)

**Comment by haocibuni** [comment]
在torch==1.9 torch_geometric==2.0.4 num_workers=0的情况下，能够对原始数据分析并加载进模型，但会出现第二个报错，edge_index实例如下图所示：
![image](https://user-images.githubusercontent.com/36734979/163676889-50b469ed-3c4f-49df-bc27-ab77cc2aa0b6.png)

**Comment by cszhangzhen** [comment]
我没有在windows上运行过这个代码，数据加载现在不报错了？感觉你这数据加载的不对呀, edge_index肯定是2 x|e|的大小.

**Comment by haocibuni** [comment]
> 我没有在windows上运行过这个代码，数据加载现在不报错了？

对呀，文件目录对的话，按理说processed应该没问题

**Comment by cszhangzhen** [comment]
那为啥现在又不报错了？之前为啥会报错？

**Comment by haocibuni** [comment]
> 那为啥现在又不报错了？之前为啥会报错？

之前装低版本的torch torch_geometric，不能对数据进行process，即出现第一个报错，并不是文件路径分隔符；现在安装高版本的orch torch_geometric，出现process的edge_index有错误，数据无法加载到模型，即第二个报错，太难受喽

**Comment by cszhangzhen** [comment]
新版本pytorch geometric中sort_edge_index函数发生了变化，我已经更新了代码，你重新下载一下吧

**Comment by haocibuni** [comment]
还需要对类型转换:data = Data(x=x, edge_index=pt_edge_index.long()) 应该可以跑了 谢谢喽

**Comment by cszhangzhen** [comment]
不客气，有问题随时提issue哈
