### ISSUE TITLE
关于模型应用场景

### ISSUE THREAD

**Issue by 280777510** [cszhangzhen/H2MN#6]
作者您好，您的论文想法很酷，读完后有个疑问。
（1）可否在大规模图上进行应用，例如大分子（含有上百个结点），计算它们之间相似性时候时间复杂度会如何？

**Comment by cszhangzhen** [comment]
你好，

该方法可以应用于大分子图上相似度的计算，可能训练时需要一点儿时间，但是做inference还是很快的。

**Comment by 280777510** [comment]
> 

好的，感谢回复。Thanks♪(･ω･)ﾉ
