### ISSUE TITLE
数据集替换

### ISSUE THREAD

**Issue by Yzuy** [cszhangzhen/H2MN#7]
您好，感谢您的开源！
我希望尝试在其他数据集上运行您模型的分类任务，因此我试图参考您提供的数据集的结构来调整我的数据集的结构。
但您的数据集中似乎只包含不同函数的CFG，我并没有在数据集中发现不同CFG之间关系的label，请问这个label是如何生成的呢？

**Comment by cszhangzhen** [comment]
Hi,

谢谢你的提问。在这个数据集中我们做的是一个binary classification，即判断这两个CFG是不是由同一段source code编译而来(不同的CFG由同一段source code经过不同的编译器以及编译等级生成)，因此我们的数据集中的label包含了这样的信息：如果两个CFG是由同一段source code生成则他们的label是1，否则为-1。

你问题中不同CFG应该说的是由不同source code生成的，那他们的label就是-1，你只需要随机抽取不同的图构建负样本就行。

**Comment by Yzuy** [comment]
哦，我想我明白您的意思了，谢谢您的解答！
