### ISSUE TITLE
Subgraph Matching Layer

### ISSUE THREAD

**Issue by ArkadiyD** [cszhangzhen/H2MN#9]
I'm sorry if I'm missing something obvious, but in the code, I can't find the implementation of the Subgraph Matching Layer (with the cosine similarity between hyperedge representations) as described in the paper, Section 3.6. I'm curious about this part of the H2MN architecture, so, could you please point to the corresponding section in the code? Thanks!

**Comment by cszhangzhen** [comment]
Hi,

The subgraph matching layer is formulated as a cross-graph propagation at [here](https://github.com/cszhangzhen/H2MN/blob/71712acc6f917f399d9f8d3eb1ee31ebbdf9db39/layers.py#L219).

Thanks for your interest.

**Comment by ArkadiyD** [comment]
Thanks for your reply!
